# this is simply copied over from config/config_designers.yml

# project definitions
project: onyourmarks
audience: writers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/designers
topnav_title: OnYourMarks Documentation
homepage_title: OnYourMarks Documentation
site_title: OnYourMarks Documentation
project_folder: mydoc
company_name: Codiserve
footer_image_location: ../../common_images/company_logo.png
github_editme_path: codiserve/documentation-theme-jekyll/edit/reviews
disqus_shortname: codiserve
# variables


sidebar_tagline: Designers
sidebar_version: Version 4.0
theme_file: theme-blue.css
pdf_file_name: mydoc_designers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: jus@codiserve.com

# these settings should work, but they don't seem to apply the right highlighting

#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  auto_ids: true
#  hard_wrap: false
#  syntax_highlighter: rouge

highlighter: pygments
markdown: kramdown

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

